apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/version: 0.7.5
    prometheus.io/operator: "true"
  name: pyrra-api
  namespace: test-mika
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: pyrra
