apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/version: 0.7.5
  name: pyrra-api
  namespace: test-mika
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: pyrra
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/name: pyrra
        app.kubernetes.io/version: 0.7.5
    spec:
      containers:
      - args:
        - api
        - --api-url=http://pyrra-kubernetes.test-mika.svc.cluster.local:9444
        - --prometheus-url=http://prometheus-operator-kube-p-prometheus.prometheus-operator.svc.cluster.local:9090
        image: ghcr.io/pyrra-dev/pyrra:v0.7.5
        name: pyrra
        ports:
        - containerPort: 9099
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: pyrra-api
