apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    prometheus.io/operator: "true"
  name: kubelet-request-errors
  namespace: test-mika
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: rest_client_requests_total{job="kubelet",code=~"5.."}
      total:
        metric: rest_client_requests_total{job="kubelet"}
  target: "99"
  window: 2w
