apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    prometheus.io/operator: "true"
  name: kubelet-runtime-errors
  namespace: test-mika
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: kubelet_runtime_operations_errors_total{job="kubelet"}
      total:
        metric: kubelet_runtime_operations_total{job="kubelet"}
  target: "99"
  window: 2w
