apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    prometheus.io/operator: "true"
  name: prometheus-operator-http-errors
  namespace: test-mika
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: prometheus_operator_kubernetes_client_http_requests_total{job="prometheus-operator",status_code=~"5.."}
      total:
        metric: prometheus_operator_kubernetes_client_http_requests_total{job="prometheus-operator"}
  target: "99.5"
  window: 2w
